### ISSUE TITLE
Java not found. Please install Java 1.8 and place it on your path

### ISSUE THREAD

**Issue by MingChen0919** [bcuser30/ML_GalaxyQueue#4]
###System information
Please enter the following information (if able). 

**Galaxy Instance: test*

### Issue description 
**tool**: statonlab_interproscan
**input**:   https://raw.githubusercontent.com/ebi-pf-team/interproscan/master/core/jms-implementation/support-mini-x86-32/test_proteins.fasta

<img width="1290" alt="screen shot 2018-05-30 at 2 31 13 pm" src="https://user-images.githubusercontent.com/1262709/40740192-283957a6-6416-11e8-9bb2-f32eb58e5a91.png">

The job will finish without showing error on the galaxy history. the error message is in the log file from the output.

<img width="1293" alt="screen shot 2018-05-30 at 2 32 47 pm" src="https://user-images.githubusercontent.com/1262709/40740274-6d0dfcc4-6416-11e8-83c9-3f8402e2e4bc.png">

**Comment by heh30** [comment]
is job-script.sh something you've generated or is it galaxy generated?

**Comment by MingChen0919** [comment]
it's generated by the galaxy tool.

**Comment by heh30** [comment]
Okay.  I'll see if there's a way to adjust it or if there's an alternative. 

Basically, as single line: 'module load java' needs to be added before the interproscan script so it the proper environment variable is loaded.

**Comment by MingChen0919** [comment]
do I have access to test galaxy server? If yes, I can do this. If not, you can find the "interproscan.Rmd" file within the **aurora_statonlab_interproscan** tool.

You can find the job-script.sh content within that file. You can add 'module load java' like below:

```
#---- build job script ----
cat >temp.sh <<EOL

module load java

/opt/main/InterProScan/5.28-67.0/interproscan.sh \\
  -i ${X_A} \\
  -f ${X_B} \\
  --disable-precalc ${X_C} \\
  --iprlookup ${X_D} \\
  --goterms ${X_E} \\
  --pathways ${X_F} \\
  --tempdir ${X_d}/temp_dir \\
  --output-dir ${X_d}/output_dir > /dev/null 2>&1
  
EOL
```

**Comment by heh30** [comment]
You should have access.  I ended up having to handle this a little differently than I originally expected.  My job appears to be running, so I'll update with results when it completes.

To resolve this, I updated the environment_setup_file variable in the galaxy.yml file (yml in 18.05 rather than .ini seen in 17.09).  It references an file located in the /main/sites/galaxy/test-galaxy directory where I'll update the PATH environment variable so the cluster nodes can 'see' the proper executable.

I used this as my guide https://biostar.usegalaxy.org/p/10367/ but it still wasn't recognizing the module command like it should have.  I'll continue research, but a workaround is in place.

**Comment by heh30** [comment]
Update:  looks like my job completed successfully.  Let me know if it works for you.

**Comment by MingChen0919** [comment]
Good to know, thanks. Yes, i have access. But I can't edit files.

It's working now. I am closing this issue.
